version: '3.8'

services:
  # Backend service
  backend:
    build: ./server
    container_name: suno-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - NODE_ENV=production
    volumes:
      - ./server/logs:/app/logs
    networks:
      - suno-network

  # Frontend service
  frontend:
    build: ./client
    container_name: suno-frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - suno-network

networks:
  suno-network:
    driver: bridge
